---
title: "p8105_hw2_bw2595"
author: "Blair Wigsten"
date: "9/25/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

```{r}
library(readxl)
trashwheel_data = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 1) %>%
  janitor::clean_names() %>%
  select(-x15, -x16, -x17) %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = as.integer(round(sports_balls, 0)))
```

```{r}
precip_2018 = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 5, skip = 1) %>%
  janitor::clean_names() %>%
  drop_na() %>%
  mutate(year = 2018)
```

```{r}
precip_2017 = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 6, skip = 1) %>%
  janitor::clean_names() %>%
  drop_na() %>%
  mutate(year = 2017)
```

```{r}
precip_2017_2018 =
  bind_rows(precip_2017, precip_2018) %>%
  janitor::clean_names() %>%
  arrange(month) %>%
  mutate(
    month = as.numeric(month), 
    month = month.abb[month])
```

There are `r nrow(precip_2017_2018)` observations in the combined precipitation dataset and `r nrow(trashwheel_data)` observations in the trashwheel dataset. . The total precipitation in 2018 was `r sum(pull(precip_2018, total))`. 
*key observations and median sports balls in 2017*

```{r}
pols_month = read_csv(file = "fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day")) %>%
  mutate(
    month = as.numeric(month), 
    month = month.abb[month],
    prez_gop = recode(prez_gop, `1` = "gop", `0` = "dem", `2` = "gop"),
    president = prez_gop) %>%
  select(-day)
```

```{r}
snp = read_csv(file = "fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c("day", "month", "year")) %>%
  arrange(year, month) %>%
  mutate(
    month = as.numeric(month),
    month = month.abb[month]) %>%
  select(year, month, close)
```

```{r}
unemployment = read.csv(file = "fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment rate") %>%
  rename(year = Year) %>%
  mutate(
    year = as.character(year))
```

```{r}
snp_pols = 
  left_join(pols_month, snp, by = c("year", "month"))
```

```{r}
final_data = left_join(snp_pols, unemployment, by = c("year", "month"))
```






